- name: create deployment user
  user: name={{ deploy_user }} comment="Application deployment user"

- authorized_key: user={{ deploy_user }} key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: ensure config directory is present
  command: mkdir -p {{ config_directory }}
  become: yes
  become_method: sudo
  become_user: "{{ deploy_user }}"
